//This amazing design and code generated by Figma AI

import { motion } from "framer-motion";
import { MessageCircle, Users, Globe2, Sparkles } from "lucide-react";
import { Button } from "./banner-components/Button";
import { ChatBubbles } from "./banner-components/ChatBubbles";
import { FloatingElements } from "./banner-components/FloatingElements";
import { GlobeWithConnections } from "./banner-components/GlobeWithConnections";
import { LandmarkIcons } from "./banner-components/LandmarkIcons";
import { LanguageFlags } from "./banner-components/LanguageFlags";
import { Link } from "react-router";
import { toast } from "react-hot-toast";

export function HeroBanner() {
  return (
    <div className="relative min-h-screen bg-gradient-to-br from-indigo-900 via-blue-900 to-purple-900 overflow-hidden">
      {/* Background decorative elements */}
      <FloatingElements />
      {/* Main content */}
      <div className="relative z-10 container mx-auto px-4 py-20">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Left side - Text content */}
          <motion.div
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8 }}
            className="space-y-6"
          >
            {/* Badge */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/20 backdrop-blur-md border border-white/30"
            >
              <Sparkles className="w-4 h-4 text-yellow-300" />
              <span className="text-white">
                Connect with 10M+ learners worldwide
              </span>
            </motion.div>

            {/* Main heading */}
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="text-white text-5xl md:text-6xl font-extrabold leading-tight" // Added text sizing
            >
              Learn Languages Through Real Conversations
            </motion.h1>

            {/* Subheading */}
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
              className="text-blue-100 text-xl max-w-md"
            >
              Connect with native speakers around the world. Practice languages
              naturally through chat, video calls, and cultural exchange.
            </motion.p>

            {/* Features */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 }}
              className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-4"
            >
              <div className="flex flex-col items-center gap-2 p-4 rounded-xl bg-white/10 backdrop-blur-md border border-white/20 text-center">
                <Users className="w-6 h-6 text-white" />
                <span className="text-white text-sm font-medium">
                  150+ Countries
                </span>
              </div>
              <div className="flex flex-col items-center gap-2 p-4 rounded-xl bg-white/10 backdrop-blur-md border border-white/20 text-center">
                <MessageCircle className="w-6 h-6 text-white" />
                <span className="text-white text-sm font-medium">
                  50+ Languages
                </span>
              </div>
              <div className="flex flex-col items-center gap-2 p-4 rounded-xl bg-white/10 backdrop-blur-md border border-white/20 text-center">
                <Globe2 className="w-6 h-6 text-white" />
                <span className="text-white text-sm font-medium">
                  24/7 Online
                </span>
              </div>
            </motion.div>

            {/* CTA Buttons */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.6 }}
              className="flex flex-wrap gap-4 pt-6"
            >
              <Link to={"/auth/register"}>
                <Button
                  size="lg"
                  className="bg-white text-indigo-600 hover:bg-gray-100 shadow-lg"
                >
                  Get Started Free
                </Button>
              </Link>
              <Button
                onClick={() => {
                  // alert("Demo is not available yet.");
                  toast.error("Demo is not available yet.");
                }}
                size="lg"
                variant="outline"
                className="bg-transparent text-white border-white/30 hover:bg-white/10 backdrop-blur-md"
              >
                Watch Demo
              </Button>
            </motion.div>
          </motion.div>

          {/* Right side - Visual elements */}
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.8, delay: 0.3 }}
            className="relative h-[600px] flex items-center justify-center"
          >
            {/* Globe with connections in the center */}
            <GlobeWithConnections />

            {/* Landmarks around */}
            <LandmarkIcons />

            {/* Chat bubbles */}
            <ChatBubbles />

            {/* Language flags */}
            <LanguageFlags />
          </motion.div>
        </div>
      </div>
      {/* Bottom gradient overlay */}
      <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-indigo-900/30 to-transparent pointer-events-none z-40" />{" "}
    </div>
  );
}

export default HeroBanner;
